name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Or your Node.js version
        
    - name: Modify .env file
      run: |
        sed -i 's|https://localhost:44306|https://146.59.158.8:5002/|g' .env
        
    - name: Install dependencies and build
      run: |
        npm install
        npm run build
        
    - name: Display npm error log
      if: failure()   # Only runs this step if previous step failed
      run: cat /home/runner/.npm/_logs/*-debug.log
      
    - name: Deploy to VPS
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      run: |
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key
        rsync -av --delete -e "ssh -i deploy_key -o StrictHostKeyChecking=no -p 19452" ./dist/ deploy@146.59.158.8:/var/www/skills-sellers.fr/public_html/
        rm -f deploy_key
